"""Summarize method argument/return type variants from a probe report JSON.

Reads only the JSON report generated by `scripts/probe_load_json_types.py` and
produces a compact per-method type summary.

Usage:
    uv run python scripts/summarize_report_types.py
    uv run python scripts/summarize_report_types.py \
        --out scripts/reports/load_json_type_summary.json
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import TypedDict

logger = logging.getLogger(__name__)
PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REPORT_PATH = "scripts/reports/load_json_type_probe_report.json"


class MethodBucket(TypedDict):
    """Intermediate aggregation container for one method's observed types."""

    argument_types: dict[str, set[str]]
    return_types: set[str]
    return_item_types: set[str]
    return_key_types: set[str]
    return_value_types: set[str]
    return_raw_data_types: set[str]


def _get_method_bucket(store: dict[str, MethodBucket], method: str) -> MethodBucket:
    if method not in store:
        store[method] = {
            "argument_types": {},
            "return_types": set(),
            "return_item_types": set(),
            "return_key_types": set(),
            "return_value_types": set(),
            "return_raw_data_types": set(),
        }
    return store[method]


def _append_type(bucket: set[str], maybe_type: object) -> None:
    if isinstance(maybe_type, str) and maybe_type:
        bucket.add(maybe_type)


def _merge_argument_types(method_bucket: MethodBucket, args: dict[str, object]) -> None:
    argument_types = method_bucket["argument_types"]
    for arg_name, arg_summary in args.items():
        if not isinstance(arg_name, str) or not isinstance(arg_summary, dict):
            continue

        arg_type = arg_summary.get("type")
        if not isinstance(arg_type, str):
            continue

        if arg_name not in argument_types:
            argument_types[arg_name] = set()
        argument_types[arg_name].add(arg_type)


def _merge_return_types(method_bucket: MethodBucket, result: dict[str, object]) -> None:
    _append_type(method_bucket["return_types"], result.get("type"))

    item_types = result.get("item_types")
    if isinstance(item_types, list):
        for item_type in item_types:
            _append_type(method_bucket["return_item_types"], item_type)

    key_types = result.get("key_types")
    if isinstance(key_types, list):
        for key_type in key_types:
            _append_type(method_bucket["return_key_types"], key_type)

    value_types = result.get("value_types")
    if isinstance(value_types, list):
        for value_type in value_types:
            _append_type(method_bucket["return_value_types"], value_type)

    _append_type(
        method_bucket["return_raw_data_types"],
        result.get("raw_data_type"),
    )


def _resolve_path(path_arg: str) -> Path:
    path = Path(path_arg)
    return path if path.is_absolute() else PROJECT_ROOT / path


def _format_report_source(path: Path) -> str:
    try:
        return path.relative_to(PROJECT_ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def summarize_report(
    report_data: dict[str, object], *, report_source: str
) -> dict[str, object]:
    """Aggregate unique argument and return type variants per method.

    Args:
        report_data: Parsed JSON object from load_json_type_probe_report.json.
        report_source: Display path to the input report.

    Returns:
        A JSON-serializable dictionary summarizing type variants per method.
    """
    observations = report_data.get("observations")
    if not isinstance(observations, list):
        raise ValueError("Invalid report format: 'observations' must be a list.")

    methods: dict[str, MethodBucket] = {}

    for observation in observations:
        if not isinstance(observation, dict):
            continue

        method = observation.get("method")
        if not isinstance(method, str) or not method:
            continue

        method_bucket = _get_method_bucket(methods, method)

        args = observation.get("args")
        if isinstance(args, dict):
            _merge_argument_types(method_bucket, args)

        result = observation.get("result")
        if isinstance(result, dict):
            _merge_return_types(method_bucket, result)

    # Convert sets to sorted lists for JSON serialization.
    normalized_methods: dict[str, object] = {}
    for method_name, method_bucket in methods.items():
        argument_types = method_bucket["argument_types"]
        normalized_args = {
            arg_name: sorted(types_set)
            for arg_name, types_set in argument_types.items()
        }

        normalized_methods[method_name] = {
            "argument_types": normalized_args,
            "return_types": sorted(method_bucket["return_types"]),
            "return_item_types": sorted(method_bucket["return_item_types"]),
            "return_key_types": sorted(method_bucket["return_key_types"]),
            "return_value_types": sorted(method_bucket["return_value_types"]),
            "return_raw_data_types": sorted(method_bucket["return_raw_data_types"]),
        }

    return {
        "report_source": report_source,
        "methods": normalized_methods,
    }


def main() -> None:
    """Read a probe report JSON and print/write a type summary JSON."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    parser = argparse.ArgumentParser(
        description="Summarize argument/return type variants from probe report JSON."
    )
    parser.add_argument(
        "--report",
        default=DEFAULT_REPORT_PATH,
        help="Path to input probe report JSON.",
    )
    parser.add_argument(
        "--out",
        default="",
        help="Optional path to write summary JSON. If omitted, prints to stdout.",
    )
    args = parser.parse_args()

    report_path = _resolve_path(args.report)
    if not report_path.exists():
        raise FileNotFoundError(f"Report not found: {report_path}")

    report_data = json.loads(report_path.read_text(encoding="utf-8"))
    summary = summarize_report(
        report_data,
        report_source=_format_report_source(report_path),
    )

    serialized = json.dumps(summary, indent=2)
    if args.out:
        out_path = _resolve_path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(serialized, encoding="utf-8")
        logger.info("Wrote summary: %s", out_path)
        return

    sys.stdout.write(serialized + "\n")


if __name__ == "__main__":
    main()
